name = "One Dark"
author = "@bumaruf"
contributor = "@bumaruf"
source = "https://github.com/atom/atom/tree/master/packages/one-dark-syntax"
license = "MIT"
background = "#282c34"
foreground = "#abb2bf"
palette = [
  "#282c34", "#e06c75", "#98c379", "#e5c07b",
  "#61afef", "#c678dd", "#56b6c2", "#abb2bf",
  "#5c6370", "#e06c75", "#98c379", "#e5c07b",
  "#61afef", "#c678dd", "#56b6c2", "#ffffff",
]
