// src/kitty.ts

import type { Theme } from "../core/theme";
import { addImport } from "../platform/config-file";
import type { Fs } from "../platform/fs";
import type { Backend, Env, Run } from "./backend";

const INCLUDE_LINE = "include ttm-theme.conf";

function renderThemeFile(theme: Theme): string {
  const colors = theme.palette
    .map((color, i) => `color${i} ${color}`)
    .join("\n");

  return `# GENERATED BY ttm — do not edit by hand.
# Theme: ${theme.name}

background ${theme.background}
foreground ${theme.foreground}
cursor ${theme.foreground}

${colors}
`;
}

export function createKittyBackend(fs: Fs, run: Run, env: Env): Backend {
  const dir =
    env.KITTY_CONFIG_DIRECTORY ??
    `${env.XDG_CONFIG_HOME ?? `${env.HOME ?? ""}/.config`}/kitty`;

  const configPath = `${dir}/kitty.conf`;
  const themePath = `${dir}/ttm-theme.conf`;

  return {
    id: "kitty",
    name: "kitty",

    detect(e) {
      return e.KITTY_WINDOW_ID !== undefined || e.TERM === "xterm-kitty";
    },

    async isInstalled() {
      return fs.exists(configPath);
    },

    async current() {
      if (!(await fs.exists(themePath))) return null;
      const source = await fs.readFile(themePath);
      return /^# Theme: (.+)$/m.exec(source)?.[1] ?? null;
    },

    async apply(theme: Theme) {
      if (!(await fs.exists(configPath))) {
        throw new Error(
          `kitty.conf not found at ${configPath} — create it first, then run ttm again`,
        );
      }

      await fs.writeFile(themePath, renderThemeFile(theme));
      await addImport(fs, { configPath, importLine: INCLUDE_LINE });

      // Bonus kitty gives us: repaint every open window right now. Remote
      // control is often disabled, and that is fine — the config is written,
      // and new windows will use it. Failing the apply over this would be wrong.
      try {
        await run([
          "kitty",
          "@",
          "set-colors",
          "--all",
          "--configured",
          themePath,
        ]);
      } catch {
        // Remote control unavailable. Not an error.
      }
    },
  };
}
