// scripts/generate-builtin.ts
//
// Generates src/builtin-themes.ts from themes/*.toml so the compiled
// standalone binary (`bun build --compile`) always has a themes catalogue
// embedded in it, without contributors ever hand-editing the generated file.
//
// Run via `bun run scripts/generate-builtin.ts` — wired into `bun run build`.

import { readdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseTheme, type Theme } from "../src/theme";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const themesDir = join(root, "themes");
const outFile = join(root, "src", "builtin-themes.ts");

async function main() {
  const entries = await readdir(themesDir);
  const files = entries.filter((f) => f.endsWith(".toml")).sort();

  const themes: Theme[] = [];
  const seen = new Map<string, string>();

  for (const file of files) {
    const source = await Bun.file(join(themesDir, file)).text();
    // Reuses the same parseTheme() validation as loadThemes(), so a
    // malformed theme can never be embedded in the binary.
    const theme = parseTheme(source, file);
    const key = theme.name.toLowerCase();
    const previous = seen.get(key);
    if (previous) {
      throw new Error(
        `duplicate theme name "${theme.name}" in ${file} and ${previous}`,
      );
    }
    seen.set(key, file);
    themes.push(theme);
  }

  themes.sort((a, b) => a.name.localeCompare(b.name));

  const body = JSON.stringify(themes, null, 2);

  const contents = `// GENERATED FILE — do not edit by hand.
//
// Generated by scripts/generate-builtin.ts from themes/*.toml. Run
// \`bun run scripts/generate-builtin.ts\` (or \`bun run build\`, which does
// this automatically) to regenerate after changing a theme file.

import type { Theme } from "./theme";

export const BUILTIN_THEMES: Theme[] = ${body};
`;

  await Bun.write(outFile, contents);
  console.log(`wrote ${themes.length} themes to ${outFile}`);
}

await main();
