// scripts/generate-builtin.ts
//
// Generates src/builtin-themes.ts from themes/*.toml so the compiled
// standalone binary (`bun build --compile`) always has a themes catalogue
// embedded in it, without contributors ever hand-editing the generated file.
//
// Run via `bun run scripts/generate-builtin.ts` — wired into `bun run build`.

import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadThemes } from "../src/theme";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const themesDir = join(root, "themes");
const outFile = join(root, "src", "builtin-themes.ts");

async function main() {
  // Reuses loadThemes() (readdir, .toml filter, parse, dup-check, sort) so
  // the embedded catalogue and the on-disk catalogue can never drift apart.
  const themes = await loadThemes(themesDir);

  const body = JSON.stringify(themes, null, 2);

  const contents = `// GENERATED FILE — do not edit by hand.
//
// Generated by scripts/generate-builtin.ts from themes/*.toml. Run
// \`bun run scripts/generate-builtin.ts\` (or \`bun run build\`, which does
// this automatically) to regenerate after changing a theme file.

import type { Theme } from "./theme";

export const BUILTIN_THEMES: Theme[] = ${body};
`;

  await Bun.write(outFile, contents);
  console.log(`wrote ${themes.length} themes to ${outFile}`);
}

await main();
