// scripts/generate-builtin.ts
//
// Generates src/generated/builtin-themes.ts from themes/*.toml so the compiled
// standalone binary (`bun build --compile`) always has a themes catalogue
// embedded in it, without contributors ever hand-editing the generated file.
//
// Run via `bun run scripts/generate-builtin.ts` — wired into `bun run build`.

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadThemes, type Theme } from "../src/core/theme";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const themesDir = join(root, "themes", "core");
const outFile = join(root, "src", "generated", "builtin-themes.ts");

/** Pure so it can be tested: a bug here ships a binary with a wrong catalogue. */
export function renderBuiltinModule(themes: Theme[]): string {
  return `// GENERATED FILE — do not edit by hand.
//
// Generated by scripts/generate-builtin.ts from themes/*.toml. Run
// \`bun run scripts/generate-builtin.ts\` (or \`bun run build\`, which does
// this automatically) to regenerate after changing a theme file.

import type { Theme } from "../core/theme";

export const BUILTIN_THEMES: Theme[] = ${JSON.stringify(themes, null, 2)};
`;
}

async function main() {
  // Reuse loadThemes() so the embedded and on-disk catalogues cannot drift.
  const themes = await loadThemes(themesDir);

  if (themes.length === 0) {
    throw new Error(
      `no themes found in ${themesDir} — refusing to generate an empty catalogue`,
    );
  }

  await Bun.write(outFile, renderBuiltinModule(themes));
  console.log(`wrote ${themes.length} core themes to ${outFile}`);
}

if (import.meta.main) {
  await main();
}
