// src/alacritty.ts
import type { Backend, Env } from "./backend";
import { addImport } from "./config-file";
import type { Fs } from "./fs";
import type { Theme } from "./theme";

const IMPORT_LINE = 'general.import = ["ttm-theme.toml"]';

/** The theme file the ttm owns and rewrites freely. */
function renderThemeFile(theme: Theme): string {
  const p = theme.palette;
  return `# GENERATED BY ttm — do not edit by hand.
# Theme: ${theme.name}

[colors.primary]
background = "${theme.background}"
foreground = "${theme.foreground}"

[colors.normal]
black   = "${p[0]}"
red     = "${p[1]}"
green   = "${p[2]}"
yellow  = "${p[3]}"
blue    = "${p[4]}"
magenta = "${p[5]}"
cyan    = "${p[6]}"
white   = "${p[7]}"

[colors.bright]
black   = "${p[8]}"
red     = "${p[9]}"
green   = "${p[10]}"
yellow  = "${p[11]}"
blue    = "${p[12]}"
magenta = "${p[13]}"
cyan    = "${p[14]}"
white   = "${p[15]}"
`;
}

export function createAlacrittyBackend(
  fs: Fs,
  env: Env,
  platform: NodeJS.Platform,
): Backend {
  const dir =
    platform === "win32"
      ? `${env.APPDATA ?? ""}\\alacritty`
      : `${env.XDG_CONFIG_HOME ?? `${env.HOME ?? ""}/.config`}/alacritty`;

  const sep = platform === "win32" ? "\\" : "/";
  const configPath = `${dir}${sep}alacritty.toml`;
  const themePath = `${dir}${sep}ttm-theme.toml`;

  return {
    id: "alacritty",
    name: "Alacritty",

    detect(e) {
      return (
        e.ALACRITTY_WINDOW_ID !== undefined || e.TERM_PROGRAM === "alacritty"
      );
    },

    async isInstalled() {
      return fs.exists(configPath);
    },

    async current() {
      if (!(await fs.exists(themePath))) return null;
      const source = await fs.readFile(themePath);
      return /^# Theme: (.+)$/m.exec(source)?.[1] ?? null;
    },

    async apply(theme: Theme) {
      if (!(await fs.exists(configPath))) {
        throw new Error(
          `alacritty.toml not found at ${configPath} — create it first, then run ttm again`,
        );
      }

      // Our file: rewritten freely.
      await fs.writeFile(themePath, renderThemeFile(theme));

      // Their file: touched once, with a backup, and never again.
      await addImport(fs, { configPath, importLine: IMPORT_LINE });
    },
  };
}
