// GENERATED FILE — do not edit by hand.
//
// Generated by scripts/generate-builtin.ts from themes/*.toml. Run
// `bun run scripts/generate-builtin.ts` (or `bun run build`, which does
// this automatically) to regenerate after changing a theme file.

import type { Theme } from "./theme";

export const BUILTIN_THEMES: Theme[] = [
  {
    "name": "Catppuccin Mocha",
    "background": "#1e1e2e",
    "foreground": "#cdd6f4",
    "palette": [
      "#45475a",
      "#f38ba8",
      "#a6e3a1",
      "#f9e2af",
      "#89b4fa",
      "#f5c2e7",
      "#94e2d5",
      "#bac2de",
      "#585b70",
      "#f38ba8",
      "#a6e3a1",
      "#f9e2af",
      "#89b4fa",
      "#f5c2e7",
      "#94e2d5",
      "#a6adc8"
    ]
  },
  {
    "name": "Dracula",
    "background": "#282a36",
    "foreground": "#f8f8f2",
    "palette": [
      "#21222c",
      "#ff5555",
      "#50fa7b",
      "#f1fa8c",
      "#bd93f9",
      "#ff79c6",
      "#8be9fd",
      "#f8f8f2",
      "#6272a4",
      "#ff6e6e",
      "#69ff94",
      "#ffffa5",
      "#d6acff",
      "#ff92df",
      "#a4ffff",
      "#ffffff"
    ]
  },
  {
    "name": "Everforest Dark",
    "background": "#2d353b",
    "foreground": "#d3c6aa",
    "palette": [
      "#343f44",
      "#e67e80",
      "#a7c080",
      "#dbbc7f",
      "#7fbbb3",
      "#d699b6",
      "#83c092",
      "#d3c6aa",
      "#868d80",
      "#e67e80",
      "#a7c080",
      "#dbbc7f",
      "#7fbbb3",
      "#d699b6",
      "#83c092",
      "#d3c6aa"
    ]
  },
  {
    "name": "Gruvbox Dark",
    "background": "#282828",
    "foreground": "#ebdbb2",
    "palette": [
      "#282828",
      "#cc241d",
      "#98971a",
      "#d79921",
      "#458588",
      "#b16286",
      "#689d6a",
      "#a89984",
      "#928374",
      "#fb4934",
      "#b8bb26",
      "#fabd2f",
      "#83a598",
      "#d3869b",
      "#8ec07c",
      "#ebdbb2"
    ]
  },
  {
    "name": "Kanagawa",
    "background": "#1f1f28",
    "foreground": "#dcd7ba",
    "palette": [
      "#090618",
      "#c34043",
      "#76946a",
      "#c0a36e",
      "#7e9cd8",
      "#957fb8",
      "#6a9589",
      "#c8c093",
      "#727169",
      "#e82424",
      "#98bb6c",
      "#e6c384",
      "#7fb4ca",
      "#938aa9",
      "#7aa89f",
      "#dcd7ba"
    ]
  },
  {
    "name": "Nord",
    "background": "#2e3440",
    "foreground": "#d8dee9",
    "palette": [
      "#3b4252",
      "#bf616a",
      "#a3be8c",
      "#ebcb8b",
      "#81a1c1",
      "#b48ead",
      "#88c0d0",
      "#e5e9f0",
      "#4c566a",
      "#bf616a",
      "#a3be8c",
      "#ebcb8b",
      "#81a1c1",
      "#b48ead",
      "#8fbcbb",
      "#eceff4"
    ]
  },
  {
    "name": "One Dark",
    "background": "#282c34",
    "foreground": "#abb2bf",
    "palette": [
      "#282c34",
      "#e06c75",
      "#98c379",
      "#e5c07b",
      "#61afef",
      "#c678dd",
      "#56b6c2",
      "#abb2bf",
      "#5c6370",
      "#e06c75",
      "#98c379",
      "#e5c07b",
      "#61afef",
      "#c678dd",
      "#56b6c2",
      "#ffffff"
    ]
  },
  {
    "name": "Rose Pine",
    "background": "#191724",
    "foreground": "#e0def4",
    "palette": [
      "#26233a",
      "#eb6f92",
      "#31748f",
      "#f6c177",
      "#9ccfd8",
      "#c4a7e7",
      "#ebbcba",
      "#e0def4",
      "#6e6a86",
      "#eb6f92",
      "#31748f",
      "#f6c177",
      "#9ccfd8",
      "#c4a7e7",
      "#ebbcba",
      "#e0def4"
    ]
  },
  {
    "name": "Solarized Dark",
    "background": "#002b36",
    "foreground": "#839496",
    "palette": [
      "#073642",
      "#dc322f",
      "#859900",
      "#b58900",
      "#268bd2",
      "#d33682",
      "#2aa198",
      "#eee8d5",
      "#002b36",
      "#cb4b16",
      "#586e75",
      "#657b83",
      "#839496",
      "#6c71c4",
      "#93a1a1",
      "#fdf6e3"
    ]
  },
  {
    "name": "Tokyo Night",
    "background": "#1a1b26",
    "foreground": "#c0caf5",
    "palette": [
      "#15161e",
      "#f7768e",
      "#9ece6a",
      "#e0af68",
      "#7aa2f7",
      "#bb9af7",
      "#7dcfff",
      "#a9b1d6",
      "#414868",
      "#f7768e",
      "#9ece6a",
      "#e0af68",
      "#7aa2f7",
      "#bb9af7",
      "#7dcfff",
      "#c0caf5"
    ]
  }
];
