#!/usr/bin/env bun
import type { Backend } from "./backend";
import type { Theme } from "./theme";

const USAGE = `ttm — pick a terminal theme and see it live

  ttm                 open the picker
  ttm list            list available themes
  ttm current         print the active theme
  ttm apply <name>    apply a theme by name
  ttm --help          show this help`;

export async function runCli(
  argv: string[],
  backend: Backend,
  themes: Theme[],
  out: (s: string) => void,
): Promise<number> {
  const [command, ...rest] = argv;

  switch (command) {
    case "list": {
      let current: string | null = null;
      try {
        current = await backend.current();
      } catch (error) {
        out(
          `warning: could not determine the active theme (${(error as Error).message})`,
        );
      }
      for (const theme of themes) {
        out(theme.name === current ? `* ${theme.name}` : `  ${theme.name}`);
      }
      return 0;
    }

    case "current": {
      try {
        const current = await backend.current();
        out(current ?? "(none)");
      } catch (error) {
        out(
          `error: could not determine the active theme (${(error as Error).message})`,
        );
        return 1;
      }
      return 0;
    }

    case "apply": {
      const name = rest.join(" ").trim();
      if (name === "") {
        out("usage: ttm apply <name>");
        return 1;
      }
      const theme = themes.find(
        (t) => t.name.toLowerCase() === name.toLowerCase(),
      );
      if (!theme) {
        out(`unknown theme: ${name}`);
        out("");
        out("available:");
        for (const t of themes) out(`  ${t.name}`);
        return 1;
      }
      try {
        await backend.apply(theme);
      } catch (error) {
        out(`error: could not apply theme (${(error as Error).message})`);
        return 1;
      }
      out(`applied ${theme.name} (new windows will use it)`);
      return 0;
    }

    case "--help":
    case "-h":
      out(USAGE);
      return 0;

    default:
      out(`unknown command: ${command}`);
      out("");
      out(USAGE);
      return 1;
  }
}

import { dirname, join } from "node:path";
import { BUILTIN_THEMES } from "./builtin-themes";
import { createGnomeBackend, realRun } from "./gnome";
import { loadThemes } from "./theme";
import { runTui } from "./tui";

/**
 * Resolve the theme catalogue, in order:
 *   1. TTM_THEMES env var, if set — lets someone test a theme they're writing.
 *   2. A real `themes/` directory next to the source/package (the
 *      `bun run` / `npm install` cases).
 *   3. The catalogue embedded at build time, generated by
 *      scripts/generate-builtin.ts into src/builtin-themes.ts (the
 *      compiled-binary case, where `Bun.main` is a virtual `/$bunfs/...`
 *      path with nothing on disk beside it).
 */
export async function resolveThemes(
  baseDir: string = dirname(Bun.main),
): Promise<Theme[]> {
  const override = process.env.TTM_THEMES;
  if (override) return loadThemes(override);

  const onDisk = join(baseDir, "..", "themes");
  const themes = await loadThemes(onDisk);
  if (themes.length > 0) return themes;

  return BUILTIN_THEMES;
}

if (import.meta.main) {
  const backend = createGnomeBackend(realRun);
  const themes = await resolveThemes();

  if (themes.length === 0) {
    console.error(
      "no themes found (checked TTM_THEMES, the on-disk themes/ directory, and the embedded catalogue)",
    );
    process.exit(1);
  }

  const argv = process.argv.slice(2);

  if (argv.length === 0) {
    const applied = await runTui(themes, backend);
    if (applied) console.log(`applied ${applied.name}`);
    process.exit(0);
  }

  const code = await runCli(argv, backend, themes, (s) => console.log(s));
  process.exit(code);
}
